name: Deploy + E2E

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production

  e2e:
    needs: deploy
    uses: ./.github/workflows/large.yml
    with:
      environment: production
