name: Deploy + E2E

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production

  e2e:
    needs: deploy
    if: success()
    uses: ./.github/workflows/large.yml
    with:
      environment: production

  notify-on-app:
    needs: [deploy, e2e]
    if: failure()
    uses: ./.github/workflows/notify.yml
    with:
      reason: |
        *Large tests failed*
        PR:* `<${{ github.event.pull_request.html_url || github.event.pull_request.number }}>`
        Title:* ${{ github.event.pull_request.title }}
        Author:* ${{ github.event.pull_request.user.login }}
      channel_id: "${{ vars.SLACK_CHANNEL_LARGE_TEST_ID }}"
    secrets: inherit
