name: Deploy + E2E

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production

  e2e:
    needs: deploy
    if: success()
    uses: ./.github/workflows/large.yml
    with:
      environment: production

  notify-on-app:
    needs: [deploy, e2e]
    if: failure() && github.event_name == 'pull_request'
    uses: ./.github/workflows/notify.yml
    with:
      reason: "*Large tests failed*\n*Job failed en workflow:* ${{ github.workflow }}\n• *Job:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}?check_suite_focus=true|${{ github.job }}>\n• *Run:* #${{ github.run_number }}\n• *Actor:* @${{ github.actor }}"
      channel_id: "${{ vars.SLACK_CHANNEL_LARGE_TEST_ID }}"
    secrets: inherit
